npm install --save-dev @types/jest
fix `error TS2582: Cannot find name describe. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha``